- name: Clone oh-my-zsh
  git: repo={{ shellconfig_oh_my_zsh_repo }} dest={{ shellconfig_oh_my_zsh_home }} update=no
  # .zshrc will be generated later by the dotfile entries

- name: Delete custom dir if it does not contain our repo
  file: {{ shellconfig_oh_my_zsh_home }}/custom state=absent
  when: zsh_custom_repo.changed and not zsh_custom_repo.before

- name: Checkout oh-my-zsh customizations
  git: repo={{ shellconfig_oh_my_zsh_custom_repo }} dest={{ shellconfig_oh_my_zsh_home }}/custom

- name: Checkout dotfiles
  git: repo={{ shellconfig_dotfiles_repo }} dest={{ shellconfig_dotfiles_home }}
  register: dotfiles_local_repo

- name: Install dotfiles
  command: {{ shellconfig_dotfiles_home }}/install_all.sh chdir={{ shellconfig_dotfiles_home }}
  when: dotfiles_local_repo.changed

- name: ZSH facts
  shell: 'echo $SHELL'
  register: default_shell
  changed_when: False
  sudo: no

- name: Make ZSH default shell
  shell: chsh -s /usr/local/bin/zsh
  when: default_shell.stdout.find('/bin/zsh') == -1
