- name: Clone oh-my-zsh
  git: repo={{ shellconfig_oh_my_zsh_repo }} dest={{ shellconfig_oh_my_zsh_home }} update=no
  # .zshrc will be generated later by the dotfile entries

- name: Check if oh-my-zsh is customized by us
  stat: path={{shellconfig_oh_my_zsh_home}}/custom/.git
  register: zsh_custom_repo_clone

- name: Delete custom dir if it does not contain our repo
  file: name={{ shellconfig_oh_my_zsh_home }}/custom state=absent
  when: shellconfig_oh_my_zsh_custom_repo and not zsh_custom_repo_clone.stat.exists

- name: Checkout oh-my-zsh customizations
  git: repo={{ shellconfig_oh_my_zsh_custom_repo }} dest={{ shellconfig_oh_my_zsh_home }}/custom

- name: Checkout dotfiles
  git: repo={{ shellconfig_dotfiles_repo }} dest={{ shellconfig_dotfiles_home }}
  register: dotfiles_local_repo

- name: Install dotfiles
  command: "{{ shellconfig_dotfiles_home }}/install_all.sh chdir={{ shellconfig_dotfiles_home }}"
  when: dotfiles_local_repo.changed

- name: Add brew version of zsh to list of allowed shells
  lineinfile: dest=/etc/shells line='/usr/local/bin/zsh' state=present
  sudo: true

- name: Make ZSH default shell
  shell: chsh -s /usr/local/bin/zsh
  when: ansible_env.SHELL.find('/bin/zsh') == -1
