---
# Brew.
- name: Ensure configured wikimedia homebrew packages are installed.
  homebrew: "name={{ item }} state=present"
  with_items: wikimedia_brew_packages

# Casks
- name: Ensure configured wikimedia homebrew casks are installed.
  homebrew_cask: "name={{ item }} state=present"
  with_items: wikimedia_brew_casks
