---
# Brew.
- name: Ensure configured private homebrew packages are installed.
  homebrew: "name={{ item }} state=present"
  with_items: private_brew_packages

# Casks
- name: Ensure configured private homebrew casks are installed.
  homebrew_cask: "name={{ item }} state=present"
  with_items: private_brew_casks
