- include: install_software.yml
  tags: software

- include: customize_zsh.yml
  tags: shell

- name: Checkout dotfiles
  git: repo={{dotfiles_repo}} dest={{dotfiles_home}}
  register: dotfiles_repo_clone

- name: Install dotfiles
  command: "{{dotfiles_home}}/install_all.sh chdir={{dotfiles_home}}"
  when: dotfiles_repo_clone.changed
