- include: install_software.yml
  tags: software

- include: customize_zsh.yml
  tags: shell

- name: Checkout dotfiles
  git: repo=git@github.com:gbirke/dotfiles.git dest=~/.dotfiles
  register: dotfiles_repo

- name: Install dotfiles
  command: ~/.dotfiles/install_all.sh chdir=~/.dotfiles
  when: dotfiles_repo.changed
