---
# Tap.
- name: Ensure configured taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items: homebrew_taps

# Brew.
- name: Ensure configured homebrew packages are installed.
  homebrew: "name={{ item }} state=present"
  with_items: homebrew_installed_packages

- name: Upgrade all homebrew packages (if configured).
  homebrew: update_homebrew=yes upgrade_all=yes
  when: homebrew_upgrade_all_packages

# Casks
- name: Ensure configured homebrew casks are installed.
  homebrew_cask: "name={{ item }} state=present"
  with_items: homebrew_installed_casks
